### ISSUE TITLE
has some problemes with kodinerds-iptv list or with linux sdk

### ISSUE THREAD

**Issue by geosone** [andiq123/M3uCleaner#1]
could you look into the problem please as it has a problem with the list.

second dose the tool have commandline support to pot input and output file ?

ex. M3uCleaner --source /tmp/kn-kode.m3u --dest /var/www/kn-kodi-clean.m3u

this way it would be able to script the list update and free it from ip blocked iptv radio streams.

`root@media:~/M3uCleaner# dotnet run m3uCleaner.csproj
Enter the path of the file...
Give me the path of the file...
/root/kn-kodi
Warning, somthing with the app logic isn't right, needs some verification!
Press Enter to continue...

Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at m3uCleaner.FileHandler.GetChannels(String path) in /root/M3uCleaner/Handlers/FileHandler.cs:line 33
   at m3uCleaner.SignalTester.GetWorkingChannles(IProgress`1 progress, IProgress`1 currentProgress) in /root/M3uCleaner/SignalTester.cs:line 25
   at m3uCleaner.Program.Main(String[] args) in /root/M3uCleaner/Program.cs:line 28
   at m3uCleaner.Program.<Main>(String[] args)
`

https://github.com/jnk22/kodinerds-iptv

**Comment by andiq123** [comment]
Hello, Thanks for reaching out to me,
 i've made improvements,
 can you please try again following the instruction that i've added.

Thank you

**Comment by geosone** [comment]
now another problem.

`root@media:~/M3uCleaner# dotnet run m3uCleaner.csproj
Hello, this app scan all the links from your m3u file and creates a new one, with only the links that are working
Drang and drop the file Here... or paste the link
http://bit.ly/kn-kodi
Unhandled exception. System.Exception: There was an error reading the file, it might be written in another format, than expected
   at m3uCleaner.FileHandler.GetChannels(String path, FileDownloader fileDownloader) in /root/M3uCleaner/Handlers/FileHandler.cs:line 48
   at m3uCleaner.SignalTester.GetWorkingChannles(IProgress`1 progress, IProgress`1 currentProgress) in /root/M3uCleaner/SignalTester.cs:line 27
   at m3uCleaner.Program.Main(String[] args) in /root/M3uCleaner/Program.cs:line 31
   at m3uCleaner.Program.<Main>(String[] args)
root@media:~/M3uCleaner# dotnet run m3uCleaner.csproj
Hello, this app scan all the links from your m3u file and creates a new one, with only the links that are working
Drang and drop the file Here... or paste the link
/root/kn-kodi.m3u
Unhandled exception. System.Exception: There was an error reading the file, it might be written in another format, than expected
   at m3uCleaner.FileHandler.GetChannels(String path, FileDownloader fileDownloader) in /root/M3uCleaner/Handlers/FileHandler.cs:line 48
   at m3uCleaner.SignalTester.GetWorkingChannles(IProgress`1 progress, IProgress`1 currentProgress) in /root/M3uCleaner/SignalTester.cs:line 27
   at m3uCleaner.Program.Main(String[] args) in /root/M3uCleaner/Program.cs:line 31
   at m3uCleaner.Program.<Main>(String[] args)
root@media:~/M3uCleaner# dotnet run m3uCleaner.csproj
Hello, this app scan all the links from your m3u file and creates a new one, with only the links that are working
Drang and drop the file Here... or paste the link
/root/kn-kodi.m3u8
Unhandled exception. System.Exception: There was an error reading the file, it might be written in another format, than expected
   at m3uCleaner.FileHandler.GetChannels(String path, FileDownloader fileDownloader) in /root/M3uCleaner/Handlers/FileHandler.cs:line 48
   at m3uCleaner.SignalTester.GetWorkingChannles(IProgress`1 progress, IProgress`1 currentProgress) in /root/M3uCleaner/SignalTester.cs:line 27
   at m3uCleaner.Program.Main(String[] args) in /root/M3uCleaner/Program.cs:line 31
   at m3uCleaner.Program.<Main>(String[] args)
`

**Comment by andiq123** [comment]
The problem is that your file is in another format, that the one model i designed the program, i've now added an explicit error handling, so if you try now, it should tell exactly where is the problem, thanks.

**Comment by andiq123** [comment]
i will be looking in your repository with the m3u files, and make it work form there.

**Comment by geosone** [comment]
thank you.

root@media:~/M3uCleaner# dotnet run m3uCleaner.csproj -src https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi_tv_atch.m3u -dst /root/kn-clean.m3u
Hello, this app scan all the links from your m3u file and creates a new one, with only the links that are working
Unhandled exception. System.Exception: Error: Names are more than the Groups
   at m3uCleaner.FileHandler.GetChannels(String path, FileDownloader fileDownloader) in /root/M3uCleaner/Handlers/FileHandler.cs:line 48
   at m3uCleaner.SignalTester.GetWorkingChannles(IProgress`1 progress, IProgress`1 currentProgress) in /root/M3uCleaner/SignalTester.cs:line 27
   at m3uCleaner.Program.Main(String[] args) in /root/M3uCleaner/Program.cs:line 38
   at m3uCleaner.Program.<Main>(String[] args)

**Comment by geosone** [comment]
th list also contain radio streams so as far es i understand the code it would not support radio stations or any link that dont end as m3u8 or ....

**Comment by andiq123** [comment]
I think it should work now properly, thank you

**Comment by geosone** [comment]
yes it looks real good now. 

to make you even more frustrated there is a list with clearly broken design.

https://github.com/Free-IPTV/Countries

**Comment by geosone** [comment]
thank you works great

**Comment by andiq123** [comment]
fixed.

**Comment by geosone** [comment]
could you wrte me your paypal name i want to say thank you with some euros .

**Comment by andiq123** [comment]
andy.u7899@gmail.com thank you very mutch

**Comment by andiq123** [comment]
when you paste a link, inside the project folder its being created a tempFile, and thats your file

**Comment by andiq123** [comment]
thank you very mutch, for further bug fixes, you can contact me, please git pull latest commits

**Comment by geosone** [comment]
this is how the script looks like at the moment

root@media:/opt/M3uCleaner# cat /home/mario/channelgen.sh
#!/bin/bash

pushd /tmp
rm -f DE01_GERMANY.m3u
wget
https://raw.githubusercontent.com/Free-IPTV/Countries/master/DE01_GERMANY.m3u
rm -f DE02_GERMANY_Etc.m3u
wget
https://raw.githubusercontent.com/Free-IPTV/Countries/master/DE02_GERMANY_Etc.m3u
rm -f DE04_GERMANY_Pluto.m3u
wget
https://raw.githubusercontent.com/Free-IPTV/Countries/master/DE04_GERMANY_Pluto.m3u
rm -f AT01_AUSTRIA.m3u
wget
https://raw.githubusercontent.com/Free-IPTV/Countries/master/AT01_AUSTRIA.m3u
sed -e '/KT1/d' -e '/plugin/d' -e '/Uppera/d' -e '/sUPPERchannel2/d' -i
AT01_AUSTRIA.m3u
rm -f kodi.m3u
wget
https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi.m3u
popd

echo "#EXTM3U" > /srv/easyepg/combine/media/kn-rakuten-clean.m3u
pushd /opt/M3uCleaner/
git pull
dotnet run m3uCleaner.csproj -src /tmp/kodi.m3u -dest
/srv/easyepg/combine/media/kn-rakuten-clean.m3u -timeout 10
dotnet run m3uCleaner.csproj -src /tmp/AT01_AUSTRIA.m3u -dest
/srv/easyepg/combine/media/kn-rakuten-clean.m3u -timeout 10
dotnet run m3uCleaner.csproj -src /tmp/DE01_GERMANY.m3u -dest
/srv/easyepg/combine/media/kn-rakuten-clean.m3u -timeout 10
dotnet run m3uCleaner.csproj -src /tmp/DE02_GERMANY_Etc.m3u -dest
/srv/easyepg/combine/media/kn-rakuten-clean.m3u -timeout 10
dotnet run m3uCleaner.csproj -src /tmp/DE04_GERMANY_Pluto.m3u -dest
/srv/easyepg/combine/media/kn-rakuten-clean.m3u -timeout 10
popd


still looking fore a script to remove duplicate.
after the test it will become a cron.

wfg and thanks for the check script if stream is working that makes live
easyer.
MArio


Am Sa., 6. März 2021 um 17:27 Uhr schrieb andiq123 <notifications@github.com

**Comment by andiq123** [comment]
i didnt test it on linux but on windows when you use the script you need to
add double quotes, for example  dotnet run -src "tmp/kodi.m3u" and not
dotnet run -src  tmp/kodi.m3u
i think a can do another scripts, i'll just leave for tomorrow, cause im
tired,
thank you

**Comment by andiq123** [comment]
Hello i've created a new repository, with an updated version, please try it now, i've adde functionality for removing dublicates,
and a pre release for linux.
Have a great day)
https://github.com/andiq123/M3uListEditor

**Comment by geosone** [comment]
thsi wil take some time dotnet version hell.

**Comment by andiq123** [comment]
there is a compiled version for linux, you dont need dotnet, just follow the instruction, just look in releases section of the repository

**Comment by geosone** [comment]
root@media:/opt/M3uListEditor# ./UI 
A fatal error occurred. The required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/opt/M3uListEditor/].
If this is a framework-dependent application, install the runtime in the global location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [/etc/dotnet/install_location].

The .NET runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=debian.10-x64&apphost_version=5.0.3

**Comment by andiq123** [comment]
hmm, That seems weird, did you follow instruction like this?
Downloading v1.1 from tags.
Unrar the v1 arhive,
and type the commands below
![Screenshot_2021-03-07_10_40_53](https://user-images.githubusercontent.com/26097930/110245598-cc644c80-7f18-11eb-99a8-ebd7391919cc.png)

**Comment by andiq123** [comment]
maybe you lack the dotnet 5 runtime

**Comment by geosone** [comment]
/tmp/dotnet-install.sh -c 5.0  -InstallDir /opt/dotnet5.0-sdk

root@media:/opt/M3uListEditor# DOTNET_ROOT=/opt/dotnet5.0-sdk/ ./UI 
Drang and drop the file Here... or paste the link

**Comment by geosone** [comment]
Finished! 269 channels are working out of 275
And were removed 5 channels becaused were doubles.
There were 280 channels.
Now There are 275 channels.
